### ISSUE TITLE
State label overflows the state width

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/timeline-chart#224]
In certain case and zoom level the state label overflows the state width. I noticed it depends on the label string. I didn't have a good open source example, so I changed the source code to a hardcoded label `ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklomnopqrstuvxyz` in `time-graph-state.ts` method `renderLabel()`. 

It looks like for strings that start with multiple upper case characters followed lower case characters it happens. For other strings, for example all lower case, all upper case or lower case characters followed by upper case it doesn't happen.

It can be reproduced with the example app in this repository or the theia-trace-extension.

![image](https://user-images.githubusercontent.com/413424/207690974-9e86479e-142f-454d-ac6d-842fbadbb468.png)

![image](https://user-images.githubusercontent.com/413424/207688208-743b8055-1aa8-424e-9dcf-8d7e60c4fce1.png)

**Comment by hoangphamEclipse** [comment]
I was able to replicate the issue without needing to change the labels of the states. In my example, I have only lowercase letter and some special characters.

![image](https://user-images.githubusercontent.com/92533264/208512391-35d4284f-0436-4279-8823-3a8efbaca4d8.png)
