### ISSUE TITLE
Cache label's BitmapText objects

### ISSUE THREAD

**Issue by bhufmann** [eclipse-cdt-cloud/timeline-chart#228]
Every state has a label, this is a great first step, now can we make every label part of a map in the view. We can look it up at the construction time, knowing our size and text. So "HoangThuanPham" would save labels for "HoangThuanPham", "HoangThuan..." "HoangThua..." "HoangThu..." "HoangTh..." "HoangT..." "Hoang..." etc... then instead of doing a new labelobject at line 76, you make a lookup in the view.

_Originally posted by @MatthewKhouzam in https://github.com/eclipse-cdt-cloud/timeline-chart/pull/226#pullrequestreview-1224932459_

**Comment by hoangphamEclipse** [comment]
Picking up this issue.

**Comment by bhufmann** [comment]
With #242 the label drawing improved significantly. I'm closing this one for now. Please reopen if needed.
